steps:
  - name: 'adoptopenjdk/openjdk8'
    entrypoint: '/workspace/sbt'
    args: ['docker:stage']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '/workspace/target/docker/stage']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  - name: ghcr.io/jamesward/easycloudrun
    entrypoint: appsecret
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_NAME=$REPO_NAME'
      - 'ENV_NAME=APPLICATION_SECRET'
      - 'REGION=us-central1'

  - name: ghcr.io/jamesward/easycloudrun
    entrypoint: deploywithenvs
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'IMAGE_NAME=$REPO_NAME'
      - 'IMAGE_VERSION=$COMMIT_SHA'
      - 'REGION=us-central1'
      - 'DEPLOY_OPTS=--cpu=2 --memory=2Gi --timeout=1h --concurrency=250'

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
